# Generated by Django 4.2.28 on 2026-05-02 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='correct_answer',
            field=models.CharField(blank=True, default='', help_text='The answer the player must type (case-insensitive). Only used for riddle nodes.', max_length=500),
        ),
        migrations.AlterField(
            model_name='node',
            name='node_type',
            field=models.CharField(choices=[('start', 'Start'), ('passage', 'Passage'), ('riddle', 'Riddle'), ('death', 'Death'), ('ending', 'Ending'), ('checkpoint', 'Checkpoint')], default='passage', max_length=20),
        ),
    ]
