# Generated by Django 4.2.28 on 2026-05-02 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0003_story_uuid_slug_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='is_correct_path',
            field=models.BooleanField(blank=True, default=None, help_text='For riddle nodes only: True = correct answer, False = wrong answer, None = normal choice.', null=True),
        ),
        migrations.AlterField(
            model_name='story',
            name='slug',
            field=models.SlugField(blank=True, help_text='URL-friendly version of the title (auto-generated).', max_length=280),
        ),
    ]
