# Generated by Django 4.2.28 on 2026-05-04 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0004_choice_is_correct_path_alter_story_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='is_template',
            field=models.BooleanField(default=False, help_text='If True, other users can clone this story into their own projects.'),
        ),
    ]
